'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {createService,hash}=require('../cloudfunctions/idleGuide/core');
const appid='wx0000000000000000';
const code=i=>i.toString(16).padStart(24,'0').toUpperCase();
function fixture(count=30){
 let clock=1800000000000,seq=0,queue=Promise.resolve();
 let docs=new Map([['state',{version:1,capacity:30,count:0,admins:[hash('admin')],members:{},invites:Object.fromEntries(Array.from({length:count},(_,i)=>[hash(code(i+1)),{expiresAt:clock+86400000,usedBy:'',revoked:false}]))}]]);
 const clone=x=>x==null?null:JSON.parse(JSON.stringify(x));
 const store={
  // Serial transaction model exercises domain behavior, not CloudBase's real isolation.
  transaction(fn){const run=queue.then(async()=>{const snapshot=new Map(Array.from(docs,([k,v])=>[k,clone(v)]));const result=await fn({get:async k=>clone(snapshot.get(k)),set:async(k,v)=>snapshot.set(k,clone(v))});docs=snapshot;return result;});queue=run.catch(()=>{});return run;},
  read:async k=>clone(docs.get(k)),
  list:async(q,offset,limit)=>Array.from(docs.entries()).filter(([,v])=>Object.entries(q).every(([k,w])=>v[k]===w)).map(([k,v])=>({...clone(v),_id:k.replace(/^item_/, '')})).sort((a,b)=>b.createdAt-a.createdAt||b._id.localeCompare(a._id)).slice(offset,offset+limit)
 };
 const service=createService(store,{now:()=>clock,randomId:()=> (++seq).toString(16).padStart(32,'0'),activityIds:['count-clouds']});
 const call=(user,action,payload={})=>service({action,payload},{openid:user,appid});
 return {call,service,store,tick:()=>{clock+=11000;},get:()=>docs,join:(user,i)=>call(user,'redeem',{code:code(i)}),edit:fn=>fn(docs.get('state'))};
}
test('identity comes only from trusted context; forged client fields cannot join',async()=>{const f=fixture();assert.equal((await f.service({action:'redeem',payload:{code:code(1),openid:'admin'}},{})).code,'IDENTITY');assert.equal((await f.service({action:'membership'},{openid:'a',appid:'wrong'})).code,'IDENTITY');});
test('all content and moderation endpoints reject uninvited visitors',async()=>{const f=fixture();for(const action of ['list','post','comments','comment','report','mine','reviewList','moderate','members','disableMember','deleteOwn'])assert.equal((await f.call('x',action)).code,'INVITE_REQUIRED');});
test('invitation binds once and same account re-entry consumes no extra slot',async()=>{const f=fixture();assert.ok((await f.join('a',1)).active);assert.ok((await f.join('a',2)).active);assert.equal((await f.join('b',1)).code,'INVALID_INVITE');assert.equal(f.get().get('state').count,1);assert.equal(f.get().get('state').invites[hash(code(2))].usedBy,'');});
test('simultaneous use of one code admits exactly one account',async()=>{const f=fixture();const results=await Promise.all(Array.from({length:30},(_,i)=>f.join('u'+i,1)));assert.equal(results.filter(r=>r.ok).length,1);});
test('simultaneous 31 valid codes cannot exceed 30 accounts',async()=>{const f=fixture(31);const results=await Promise.all(Array.from({length:31},(_,i)=>f.join('u'+i,i+1)));assert.equal(results.filter(r=>r.ok).length,30);assert.equal(results.filter(r=>r.code==='FULL').length,1);assert.equal(f.get().get('state').count,30);});
test('lowercase, whitespace and display separators are normalized',async()=>{const f=fixture();const c=code(1).match(/.{6}/g).join('-').toLowerCase();assert.ok((await f.call('a','redeem',{code:' '+c+' '})).ok);});
test('expired and revoked invitations reject; activated member stays admitted',async()=>{const f=fixture();f.edit(s=>s.invites[hash(code(1))].expiresAt=1);f.edit(s=>s.invites[hash(code(2))].revoked=true);assert.equal((await f.join('a',1)).code,'INVALID_INVITE');assert.equal((await f.join('a',2)).code,'INVALID_INVITE');await f.join('a',3);f.edit(s=>s.invites[hash(code(3))].expiresAt=1);assert.ok((await f.call('a','membership')).active);});
test('failed redeem attempts are persisted and limited',async()=>{const f=fixture();for(let i=0;i<10;i++)assert.equal((await f.join('a',99)).code,'INVALID_INVITE');assert.equal((await f.join('a',1)).code,'TOO_MANY_ATTEMPTS');assert.equal(f.get().get('state').count,0);});
test('service fails closed with missing or wrong capacity config',async()=>{const f=fixture();f.edit(s=>s.capacity=100);assert.equal((await f.join('a',1)).code,'NOT_READY');f.get().delete('state');assert.equal((await f.call('a','membership')).code,'NOT_READY');});
test('no first visitor becomes administrator',async()=>{const f=fixture();assert.equal((await f.join('a',1)).admin,false);assert.equal((await f.call('a','reviewList')).code,'FORBIDDEN');});
test('manual moderation hides pending text and replies until approved',async()=>{const f=fixture();await f.join('admin',1);await f.join('a',2);const p=await f.call('a','post',{nickname:'闲人',text:'今天数了云',activityId:'count-clouds'});assert.equal(p.status,'pending');assert.deepEqual((await f.call('a','list')).items,[]);assert.equal((await f.call('a','moderate',{id:p.id,status:'approved'})).code,'FORBIDDEN');await f.call('admin','moderate',{id:p.id,status:'approved'});assert.equal((await f.call('a','list')).items[0].text,'今天数了云');f.tick();const c=await f.call('a','comment',{parentId:p.id,nickname:'闲人',text:'也可以什么都不做'});assert.deepEqual((await f.call('a','comments',{parentId:p.id})).items,[]);await f.call('admin','moderate',{id:c.id,status:'approved'});assert.equal((await f.call('a','comments',{parentId:p.id})).items.length,1);});
test('free chat requires no activity; rejects empty, oversized or invalid fields',async()=>{const f=fixture();await f.join('a',1);for(const payload of [{nickname:' ',text:'x'},{nickname:'a',text:' '},{nickname:'a',text:'x'.repeat(501)},{nickname:'x'.repeat(21),text:'ok'},{nickname:'a',text:'ok',activityId:'fake'}])assert.equal((await f.call('a','post',payload)).code,'INVALID_INPUT');assert.ok((await f.call('a','post',{nickname:'a',text:'只是坐一会儿'})).ok);});
test('write rate limit prevents repeated clicks and does not create extra rows',async()=>{const f=fixture();await f.join('a',1);assert.ok((await f.call('a','post',{nickname:'a',text:'hi'})).ok);assert.equal((await f.call('a','post',{nickname:'a',text:'hi'})).code,'RATE_LIMIT');assert.equal((await f.call('a','mine')).items.length,1);});
test('public feed never reveals account hashes or other pending content',async()=>{const f=fixture();await f.join('admin',1);await f.join('a',2);const p=await f.call('a','post',{nickname:'a',text:'hello'});await f.call('admin','moderate',{id:p.id,status:'approved'});const json=JSON.stringify(await f.call('a','list'));assert.ok(!json.includes(hash('a')));assert.ok(!json.includes('owner'));assert.ok(!json.includes('invites'));assert.equal((await f.call('admin','mine')).items.length,0);});
test('accepted reports hide content, report reason stays private, reviewer gets context',async()=>{const f=fixture();await f.join('admin',1);await f.join('a',2);const p=await f.call('a','post',{nickname:'a',text:'hello'});await f.call('admin','moderate',{id:p.id,status:'approved'});f.tick();const report=await f.call('a','report',{targetId:p.id,reason:'不适合展示'});const review=await f.call('admin','reviewList');assert.equal(review.items[0].context,'a：hello');assert.equal((await f.call('a','list')).items.length,1);await f.call('admin','moderate',{id:report.id,status:'approved'});assert.equal((await f.call('a','list')).items.length,0);});
test('owner can delete text, others cannot; hidden parent blocks reply reads/writes',async()=>{const f=fixture();await f.join('admin',1);await f.join('a',2);const p=await f.call('a','post',{nickname:'a',text:'hello'});await f.call('admin','moderate',{id:p.id,status:'approved'});assert.equal((await f.call('admin','deleteOwn',{id:p.id})).code,'FORBIDDEN');await f.call('a','deleteOwn',{id:p.id});assert.equal(f.get().get('item_'+p.id).text,'');assert.equal((await f.call('a','comments',{parentId:p.id})).code,'NOT_FOUND');assert.equal((await f.call('admin','moderate',{id:p.id,status:'approved'})).code,'NOT_FOUND');});
test('suspension closes API access without freeing slot or reusing invitation',async()=>{const f=fixture();await f.join('admin',1);await f.join('a',2);await f.call('admin','disableMember',{memberId:hash('a'),disabled:true});assert.equal((await f.call('a','list')).code,'DISABLED');assert.equal((await f.join('a',3)).code,'DISABLED');assert.equal((await f.join('b',2)).code,'INVALID_INVITE');assert.equal(f.get().get('state').count,2);await f.call('admin','disableMember',{memberId:hash('a'),disabled:false});assert.ok((await f.call('a','membership')).active);});
test('pagination returns each approved post once with stable tie ordering',async()=>{const f=fixture();await f.join('admin',1);for(let i=0;i<25;i++){f.tick();if(i===20)f.get().delete('rate_'+hash('admin'));const p=await f.call('admin','post',{nickname:'a',text:'n'+i});assert.ok(p.ok);await f.call('admin','moderate',{id:p.id,status:'approved'});}const a=await f.call('admin','list'),b=await f.call('admin','list',{offset:20});assert.equal(a.items.length,20);assert.equal(b.items.length,5);assert.equal(new Set([...a.items,...b.items].map(x=>x.id)).size,25);});
test('database transaction failure does not create membership',async()=>{const f=fixture();f.store.transaction=async()=>{throw new Error('database offline');};await assert.rejects(f.join('a',1),/offline/);assert.equal(f.get().get('state').count,0);});
