'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const root=path.resolve(__dirname,'../miniprogram');
const cloud=require('../miniprogram/utils/cloud');
const originalCall=cloud.call;
let definition,app;
function instance(route){
 global.Page=d=>{definition=d;};const file=path.join(root,route+'.js');delete require.cache[file];require(file);
 return {...definition,route,data:JSON.parse(JSON.stringify(definition.data)),setData(updates){for(const [key,value]of Object.entries(updates)){const fields=key.replace(/\[(\d+)\]/g,'.$1').split('.');let target=this.data;for(const field of fields.slice(0,-1))target=target[field]||(target[field]={});target[fields.at(-1)]=value;}}};
}
function setup(){
 const calls=[],storage=new Map();app={globalData:{cloudReady:true,returnPath:''}};
 global.getApp=()=>app;
 global.wx={reLaunch:o=>calls.push(['launch',o.url]),switchTab:o=>calls.push(['tab',o.url]),navigateTo:o=>calls.push(['nav',o.url]),showToast:()=>{},getStorageSync:k=>storage.get(k),setStorageSync:(k,v)=>storage.set(k,v),setNavigationBarTitle:()=>{},showModal:o=>o.success({confirm:true,content:'骚扰'})};
 return calls;
}
test('all six routes parse and every WXML handler exists',()=>{setup();const config=require('../miniprogram/app.json');assert.equal(config.pages.length,6);for(const route of config.pages){const p=instance(route);for(const ext of ['json','wxss','wxml'])assert.ok(fs.existsSync(path.join(root,route+'.'+ext)));const xml=fs.readFileSync(path.join(root,route+'.wxml'),'utf8');for(const m of xml.matchAll(/\b(?:bind|catch)[\w:]*="([\w]+)"/g))assert.equal(typeof p[m[1]],'function',route+'/'+m[1]);}});
test('deep link content remains hidden until server membership succeeds',async()=>{setup();let finish;cloud.call=()=>new Promise(r=>{finish=r;});const p=instance('pages/detail/detail');p.onLoad({id:'paper-slap'});const task=p.onShow();assert.equal(p.data.authorized,false);assert.equal(p.data.item,null);finish({active:true});await task;assert.equal(p.data.authorized,true);assert.equal(p.data.item.id,'paper-slap');});
test('uninvited deep link redirects and keeps requested detail route',async()=>{const calls=setup();cloud.call=async()=>({active:false});const p=instance('pages/detail/detail');p.onLoad({id:'paper-slap'});await p.onShow();assert.equal(p.data.item,null);assert.equal(calls[0][1],'/pages/invite/invite');assert.equal(app.globalData.returnPath,'/pages/detail/detail?id=paper-slap');});
test('offline membership never falls back to local cached access',async()=>{setup();cloud.call=async()=>{throw new Error('offline');};const p=instance('pages/home/home');p.onLoad({});await p.onShow();assert.equal(p.data.authorized,false);assert.equal(p.data.accessMessage,'offline');p.onRandom();assert.equal(p.data.list.length,0);});
test('returning to a page rechecks membership and hides suspended content',async()=>{const calls=setup();let active=true;cloud.call=async()=>({active});const p=instance('pages/home/home');p.onLoad({});await p.onShow();assert.equal(p.data.list.length,40);p.onHide();active=false;await p.onShow();assert.equal(p.data.authorized,false);assert.equal(calls.at(-1)[1],'/pages/invite/invite');});
test('late membership response cannot reopen a hidden page',async()=>{setup();let finish;cloud.call=()=>new Promise(r=>finish=r);const p=instance('pages/home/home');p.onLoad({});const pending=p.onShow();p.onHide();finish({active:true});await pending;assert.equal(p.data.authorized,false);});
test('invite requires consent, clears successful code, and restores shared detail',async()=>{const calls=setup(),api=[];cloud.call=async(a,p)=>{api.push([a,p]);return {active:true};};const p=instance('pages/invite/invite');p.setData({checking:false,code:'SAMPLE'});await p.redeem();assert.equal(api.length,0);p.onConsent({detail:{value:['agree']}});app.globalData.returnPath='/pages/detail/detail?id=paper-slap';await p.redeem();assert.equal(api[0][0],'redeem');assert.equal(p.data.code,'');assert.equal(calls.at(-1)[1],'/pages/detail/detail?id=paper-slap');});
test('community composer is folded, arbitrary chat allowed, failed text is preserved',async()=>{setup();const api=[];cloud.call=async(a,p)=>{api.push([a,p]);if(a==='membership')return {active:true};if(a==='list')return {items:[],more:false};if(a==='post')throw new Error('offline');return {};};const p=instance('pages/community/community');p.onLoad({});await p.onShow();assert.equal(p.data.composer,false);p.setData({text:'随便说说',nickname:'路人'});await p.submit();assert.equal(api.at(-1)[1].activityId,'');assert.equal(p.data.text,'随便说说');assert.equal(p.data.sending,false);assert.equal(p.data.message,'offline');});
test('community posts pending message and preserves nickname after successful submit',async()=>{setup();cloud.call=async a=>a==='membership'?{active:true}:a==='list'?{items:[],more:false}:{status:'pending'};const p=instance('pages/community/community');p.onLoad({});await p.onShow();p.setData({text:'数云',nickname:'路人'});await p.submit();assert.equal(p.data.text,'');assert.equal(p.data.nickname,'路人');assert.match(p.data.message,/审核/);});
test('authorized activity filtering and saved state still work',async()=>{setup();cloud.call=async()=>({active:true});const p=instance('pages/home/home');p.onLoad({});await p.onShow();p.onChipTap({currentTarget:{dataset:{group:'company',value:'group'}}});assert.equal(p.data.list.length,23);p.onFavTap({currentTarget:{dataset:{id:'paper-slap'}}});const s=instance('pages/saved/saved');s.onLoad({});await s.onShow();assert.equal(s.data.list[0].id,'paper-slap');});
test('cloud client translates backend errors and transport errors without leaking details',async()=>{setup();cloud.call=originalCall;wx.cloud={callFunction:({success})=>success({result:{ok:false,code:'INVALID_INVITE'}})};await assert.rejects(cloud.call('redeem'),/邀请码/);wx.cloud.callFunction=({fail})=>fail({token:'never show'});await assert.rejects(cloud.call('membership'),/连接不上/);});
